### PR TITLE
Assorted fixes

### LINKED ISSUE #3: Immediate failure if no haiku katana is available
After I worked around the error in #2 by setting stashClan to something, I then get the following:
```
> call scripts\garbage-collector\garbo.js

Using adventure value 5000.
Collecting garbage!

Autoattack is disabled.
CCS set to garbo
Refreshing stash contents...
Stash list retrieved.
Pulling items from stash...
Transfer failed for haiku katana
Movement of items failed.
JavaScript exception: Script interrupted. (file:/D:/KoLmafia1/scripts/garbage-collector/garbo.js#5097)
at file:/D:/KoLmafia1/scripts/garbage-collector/garbo.js:5097 (f)
at file:/D:/KoLmafia1/scripts/garbage-collector/garbo.js:5191
at file:/D:/KoLmafia1/scripts/garbage-collector/garbo.js:5137 (withClan)
at file:/D:/KoLmafia1/scripts/garbage-collector/garbo.js:5168 (take)
at file:/D:/KoLmafia1/scripts/garbage-collector/garbo.js:5125 (withStash)
at file:/D:/KoLmafia1/scripts/garbage-collector/garbo.js:4016 (main)
```
This was run on a Pastamancer. I am assuming it wouldn't fail like that on a Seal Clubber but I'll check when I next ascend that account as one.

### PR DESCRIPTION
**Pull request by Phillammon**
- Update libram
- Check we have source terminal before attempting to do source terminal things
- If we lack fury, do not try to furious wallop
- Fallback to a leprechaun-like if we can't find a good rotating familiar, or failing that no familiar at all
- Actually use seal figurines instead of looping forever
- Don't try to use familiars we don't own
- Don't try to use a witchess board we don't own
- Move moveable feast stashing/unstashing where it can do less damage

UPDATE:
- Now moves moveable feast at same time as before, but
- Stash failures no longer lead to immediate abort. Resolves #3

### CODE REVIEW

File: src/combat.ts [hunk 1]
```diff
@@ -65,7 +66,7 @@ export class Macro extends LibramMacro {
       get("retroCapeSuperhero") === "robot" &&
       get("retroCapeWashingInstructions") === "kill" &&
       itemType(equippedItem($slot`weapon`)) === "pistol";
-
+
```
Comment (phulin) [inline src/combat.ts:69]: Please run prettier

File: src/familiar.ts [hunk 2]
```diff
@@ -89,5 +89,11 @@ export function freeFightFamiliar(): Familiar {
     familiarValue.push([$familiar`Stocking Mimic`, mimicValue]);
   }
 
+  for (const familiar of $familiars`Robortender, Hobo Monkey, Cat Burglar, Leprechaun`) {
```
Comment (phulin) [inline src/familiar.ts:92]: Robortender should be a higher value than 1 since it drops candy and junk - maybe 200 is a good estimate?

File: src/fights.ts [hunk 3]
```diff
@@ -107,6 +109,7 @@ export function dailyFights() {
         }
 
         if (
+          SourceTerminal.have() &&
```
Comment (phulin) [inline src/fights.ts:112]: unnecessary - this is just making sure there is no digitize monster up

File: src/fights.ts [hunk 4]
```diff
@@ -256,7 +256,7 @@ const freeFightSources = [
           : $item`figurine of an ancient seal`;
       retrieveItem(1, figurine);
       retrieveItem(1, $item`seal-blubber candle`);
-      // FIXME: Some problem with mafia tracking here.
+	    use(figurine);
```
Comment (phulin) [inline src/fights.ts:259]: pls run prettier, tabs are messed up

File: src/index.ts [hunk 5]
```diff
@@ -266,7 +266,7 @@ export function main(argString = "") {
   cliExecute("ccs garbo");
 
   // FIXME: Dynamically figure out pointer ring approach.
-  withStash($items`haiku katana, repaid diaper`, () => {
+  withStash($items`haiku katana, repaid diaper, moveable feast`, () => {
```
Comment (phulin) [inline src/index.ts:269]: I don't want to take out the moveable feast for the entire duration of farming if we can avoid it. Can you change withStash to just not pull if it's not available?

**Review by phulin — CHANGES_REQUESTED** [review]

File: src/index.ts (hunk 5 above)
Comment (Phillammon) [reply src/index.ts]: Addressed as of 15879b0

File: src/fights.ts (hunk 4 above)
Comment (Phillammon) [reply src/fights.ts]: Addressed as of 15879b0

File: src/fights.ts (hunk 3 above)
Comment (Phillammon) [reply src/fights.ts]: Addressed as of 15879b0

File: src/familiar.ts (hunk 2 above)
Comment (Phillammon) [reply src/familiar.ts]: Not yet addressed- I feel like I'd want to address this as a separate familiar valuing PR, this is definitely just a bandage to make sure that something sensible comes up. My temptation is to make this a new issue that I can work on at a later date?

File: src/combat.ts (hunk 1 above)
Comment (Phillammon) [reply src/combat.ts]: Addressed as of 15879b0

**Review by phulin — APPROVED** [review]
