### PR TITLE
Free fight fixes

### LINKED ISSUE #7: Abort during Drunk Pygmy farming
```
Visit to HiddenCity: The Hidden Bowling Alley in progress...

[7815] The Hidden Bowling Alley
Encounter: drunk pygmy
Preference _lastCombatStarted changed from 20210509044352 to 20210509044353
Round 0: Player Two loses initiative!
Round 1: Player Two wins the fight!
After Battle: A love grub shyly approaches you and hands you some extra Meat.
After Battle: You look to the sky just in time to catch a glimpse of a falling star. Lucky! Well, not really lucky, because you totally knew it was going to be there.
After Battle: You think you see a weird thing out of the corner of your eye, but it turns out to be nothing. Which is actually pretty weird, if you think about it, man.
After Battle: You gain 2 Mysteriousness
This combat did not cost a turn
Preference _drunkPygmyBanishes changed from 9 to 10

Maximizer: Familiar Weight, equip Fourth of May Cosplay Saber, 400 bonus lucky gold ring, 250 bonus Mr. Cheeng's spectacles, 100 bonus pantogram pants
Preference maximizerMRUList changed from Familiar Weight, -equip broken champagne bottle, 400 bonus lucky gold ring, 250 bonus Mr. Cheeng's spectacles, 100 bonus pantogram pants;disco style 6 min;sea, 10.25 Meat Drop, 0 Item Drop, -equip broken champagne bottle, -equip unwrapped knock-off retro superhero cape, -equip cheap sunglasses, 400 bonus lucky gold ring, 300 bonus mafia thumb ring, 250 bonus Mr. Cheeng's spectacles, 100 bonus pantogram pants;2.75 Meat Drop, 0.72 Item Drop, equip Kramco Sausage-o-Matic™, equip ice nine, equip mafia pointer finger ring, -equip broken champagne bottle, -equip unwrapped knock-off retro superhero cape, 400 bonus lucky gold ring, 300 bonus mafia thumb ring, 250 bonus Mr. Cheeng's spectacles, 100 bonus pantogram pants to Familiar Weight, equip Fourth of May Cosplay Saber, 400 bonus lucky gold ring, 250 bonus Mr. Cheeng's spectacles, 100 bonus pantogram pants;Familiar Weight, -equip broken champagne bottle, 400 bonus lucky gold ring, 250 bonus Mr. Cheeng's spectacles, 100 bonus pantogram pants;disco style 6 min;sea, 10.25 Meat Drop, 0 Item Drop, -equip broken champagne bottle, -equip unwrapped knock-off retro superhero cape, -equip cheap sunglasses, 400 bonus lucky gold ring, 300 bonus mafia thumb ring, 250 bonus Mr. Cheeng's spectacles, 100 bonus pantogram pants;2.75 Meat Drop, 0.72 Item Drop, equip Kramco Sausage-o-Matic™
Maximizing...
40 combinations checked, best score 870.00
Preference libram_savedMacro changed from to skill Sing Along;if monstername garbage tourist;if hasskill Gallapagosian Mating Call;skill Gallapagosian Mating Call;endif;endif;skill Curse of Weaksauce;while !pastround 10;use seal tooth;endwhile;if hasskill Curse of Weaksauce;skill Curse of Weaksauce;endif;attack;repeat
Preference libram_savedMacro changed from skill Sing Along;if monstername garbage tourist;if hasskill Gallapagosian Mating Call;skill Gallapagosian Mating Call;endif;endif;skill Curse of Weaksauce;while !pastround 10;use seal tooth;endwhile;if hasskill Curse of Weaksauce;skill Curse of Weaksauce;endif;attack;repeat to skill Use the Force

Visit to HiddenCity: The Hidden Bowling Alley in progress...

[7815] The Hidden Bowling Alley
Encounter: drunk pygmy
Preference _lastCombatStarted changed from 20210509044353 to 20210509044354
Round 0: Player Two loses initiative!
skill Use the Force
Round 1: Player Two executes a macro!
Preference lastEncounter changed from drunk pygmy to Using the Force
Encounter: Using the Force
Running choiceAdv.ash
Submitting option 3 for choice 1387
Preference _saberForceUses changed from 0 to 1
You acquire an item: cold water bottle
You acquire an item: pygmy phone number
You acquire an item: gold Boozehounds Anonymous token

Searching for "Bowl of Scorpions"...
Search complete.
Purchasing Bowl of Scorpions (2 @ 475)...
You spent 950 Meat
You acquire Bowl of Scorpions (2)
Purchases complete.
Preference libram_savedMacro changed from to if monstername pygmy bowler;skill Snokebomb;endif;if monstername pygmy orderlies;skill Feel Hatred;endif;abort

Visit to HiddenCity: The Hidden Bowling Alley in progress...

[7815] The Hidden Bowling Alley
Preference lastEncounter changed from Using the Force to drunk pygmy
Encounter: drunk pygmy
Preference _lastCombatStarted changed from 20210509044354 to 20210509044358
Round 0: Player Two wins initiative!
Round 1: Player Two wins the fight!
After Battle: You glance in the direction of an inspiring meteor as it arcs across the sky, just as you predicted.
After Battle: You gain 5 Strengthliness
After Battle: You think you see a weird thing out of the corner of your eye, but it turns out to be nothing. Which is actually pretty weird, if you think about it, man.
After Battle: You gain 2 Mysteriousness
This combat did not cost a turn
Preference _drunkPygmyBanishes changed from 10 to 11

Preference libram_savedMacro changed from to if monstername pygmy bowler;skill Snokebomb;endif;if monstername pygmy orderlies;skill Feel Hatred;endif;abort

Visit to HiddenCity: The Hidden Bowling Alley in progress...

[7815] The Hidden Bowling Alley
Preference lastEncounter changed from drunk pygmy to tumbleweed
Encounter: tumbleweed
Preference _lastCombatStarted changed from 20210509044358 to 20210509044359
Round 0: Player Two wins initiative!
if monstername pygmy bowlerskill Snokebombendifif monstername pygmy orderliesskill Feel Hatredendifabort
Round 1: Player Two executes a macro!
KoLmafia thinks it is round 2 but KoL thinks it is round 1
You're on your own, partner.
Click here to continue in the relay browser.


JavaScript exception: Script interrupted. (file:/D:/KoLmafia1/scripts/garbage-collector/garbo.js#44602)
at file:/D:/KoLmafia1/scripts/garbage-collector/garbo.js:44602 (f)
at file:/D:/KoLmafia1/scripts/garbage-collector/garbo.js:45010 (freeFights)
at file:/D:/KoLmafia1/scripts/garbage-collector/garbo.js:45336
at file:/D:/KoLmafia1/scripts/garbage-collector/garbo.js:45754 (withStash)
at file:/D:/KoLmafia1/scripts/garbage-collector/garbo.js:45325 (main)
You are now in away mode, chat will update more slowly until you say something.
```

It is then stuck in the fight with the Tumbleweed.

### LINKED ISSUE #29: Fight a cargo shorts monster
Split off from #23

### LINKED ISSUE #37: Don't explode if janitors haven't been banished

### PR DESCRIPTION
**Pull request by Phillammon**
Assorted free fight fixes:

- Eldritch tentacle will now be fought properly even if you have an eldritch essence.
- Added %monster% ([glitch season reward name]) support.
- Added Snojo support.
- Added cargo pocket support- if we have a robortender, get a fish head, otherwise leave the pocket open.
- Fixed Jokester's Gun not being fired if we don't own a ToT Tot
- Fixed abort on pygmy bowlers if you haven't got Feel Hatred charges up, or on pygmy janitors if they show up at all
- Overhauled Drunk Pygmy logic to hopefully work better with saber and orb.
- If we haven't already used a thesis after NEP (for example, because we don't own NEP), fire off our thesis in uncle gator's- it's technically not a free kill, but +10 adventures seems worth it.
- Incidentally, sets battleAction to CCS if it is not that already, to avoid problems with people who still have "attack with weapon" set.

Resolves #7, I _hope_.
Resolves #29 
Resolves #37

### CODE REVIEW

File: src/fights.ts [hunk 1]
```diff
@@ -290,66 +303,102 @@ const freeFightSources = [
...
 
+  //Initial 9 Pygmy fights
   new FreeFight(
     () =>
-      get("questL11Worship") !== "unstarted" ? clamp(10 - get("_drunkPygmyBanishes"), 0, 10) : 0,
+      get("questL11Worship") !== "unstarted" ? clamp(9 - get("_drunkPygmyBanishes"), 0, 9) : 0,
     () => {
       putCloset(itemAmount($item`bowling ball`), $item`bowling ball`);
-      retrieveItem(10 - get("_drunkPygmyBanishes"), $item`Bowl of Scorpions`);
+      retrieveItem($item`Bowl of Scorpions`);
```
Comment (Tokoeka) [inline src/fights.ts:312]: Should this be retrieveItem(9, $item`Bowl of Scorpions`)? Or is this sequence run once for every pygmy?

File: src/fights.ts [hunk 2]
```diff
@@ -504,6 +564,32 @@ const freeFightSources = [
       ],
     }
   ),
+
+  // Not technically a free fight, but if we haven't delivered a thesis yet, we want to dump it somewhere scaling, and we have Uncle Gator's definitely available.
+  new FreeFight(
+    () => !get("_thesisDelivered") && $familiar`Pocket Professor`.experience >= 400,
```
Comment (Tokoeka) [inline src/fights.ts:570]: Are we using Prof on our Embezzlers? If so, do we not want to push delivering the thesis until after any prof copies have occured?

File: src/fights.ts (hunk 1 above)
Comment (Phillammon) [reply src/fights.ts:312]: Runs once per pygmy, but with that said it should probably retreive 9-banishes so it only performs the retrieval once

File: src/fights.ts (hunk 2 above)
Comment (Phillammon) [reply src/fights.ts]: Per discussion in discord, have made thesis use more aggressive in ef336bb so that we will be back up to full strength by the time we are at embezzlers. Not a perfect compromise, but it'll work

File: src/fights.ts (hunk 1 above)
Comment (Phillammon) [reply src/fights.ts]: Resolved as of ef336bb
